#!/usr/bin/env bash
#
# WabiSabi Installer
#
# Installs wabisabi as a global command.
# Requirements: Bun runtime (https://bun.sh)
#

set -euo pipefail

BOLD='\033[1m'
DIM='\033[2m'
CYAN='\033[36m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
RESET='\033[0m'

WABISABI_DIR="$HOME/.wabisabi"
BIN_DIR="$HOME/.local/bin"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
TERMINAL_DIR="$REPO_DIR/packages/terminal"

info()  { echo -e "  ${CYAN}>${RESET} $1"; }
ok()    { echo -e "  ${GREEN}+${RESET} $1"; }
warn()  { echo -e "  ${YELLOW}!${RESET} $1"; }
fail()  { echo -e "  ${RED}x${RESET} $1"; exit 1; }

echo ""
echo -e "  ${BOLD}WabiSabi Installer${RESET}"
echo -e "  ${DIM}AI Terminal IDE${RESET}"
echo ""

# ── Check Bun ────────────────────────────────────────────────

if ! command -v bun &>/dev/null; then
  if [ -x "$HOME/.bun/bin/bun" ]; then
    export PATH="$HOME/.bun/bin:$PATH"
  else
    fail "Bun not found. Install it: curl -fsSL https://bun.sh/install | bash"
  fi
fi

BUN_PATH="$(command -v bun)"
ok "Bun found: $BUN_PATH ($(bun --version))"

# ── Build ────────────────────────────────────────────────────

info "Building wabisabi..."

if [ ! -d "$TERMINAL_DIR" ]; then
  fail "Terminal package not found at $TERMINAL_DIR"
fi

cd "$TERMINAL_DIR"
bun install --frozen-lockfile 2>/dev/null || bun install
bun build src/index.ts --outfile dist/index.js --target bun

ok "Built successfully"

# ── Create global directories ────────────────────────────────

mkdir -p "$WABISABI_DIR"
mkdir -p "$BIN_DIR"

# ── Create launcher script ───────────────────────────────────

LAUNCHER="$BIN_DIR/wabisabi"

cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# WabiSabi launcher - generated by install.sh
exec "${BUN_PATH}" "${TERMINAL_DIR}/dist/index.js" "\$@"
LAUNCHER_EOF

chmod +x "$LAUNCHER"
ok "Launcher created: $LAUNCHER"

# ── Ensure PATH includes ~/.local/bin ────────────────────────

SHELL_NAME="$(basename "$SHELL")"
PROFILE_FILE=""

case "$SHELL_NAME" in
  zsh)  PROFILE_FILE="$HOME/.zshrc" ;;
  bash) PROFILE_FILE="$HOME/.bashrc" ;;
  fish) PROFILE_FILE="$HOME/.config/fish/config.fish" ;;
esac

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  if [ -n "$PROFILE_FILE" ] && [ -f "$PROFILE_FILE" ]; then
    if ! grep -q "\.local/bin" "$PROFILE_FILE" 2>/dev/null; then
      echo "" >> "$PROFILE_FILE"
      echo "# WabiSabi" >> "$PROFILE_FILE"
      echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$PROFILE_FILE"
      ok "Added ~/.local/bin to PATH in $PROFILE_FILE"
      warn "Run: source $PROFILE_FILE (or open a new terminal)"
    fi
  else
    warn "Add ~/.local/bin to your PATH manually"
  fi
else
  ok "~/.local/bin already in PATH"
fi

# ── Verify ───────────────────────────────────────────────────

if command -v wabisabi &>/dev/null; then
  ok "wabisabi command is available"
else
  info "wabisabi will be available after reloading your shell"
fi

# ── Done ─────────────────────────────────────────────────────

echo ""
echo -e "  ${GREEN}${BOLD}Installation complete${RESET}"
echo ""
echo -e "  ${DIM}Usage:${RESET}"
echo -e "    ${CYAN}wabisabi${RESET}              Start interactive mode"
echo -e "    ${CYAN}wabisabi config --wizard${RESET}  Configure providers"
echo -e "    ${CYAN}wabisabi --help${RESET}        Show all commands"
echo ""
